### ISSUE TITLE
Direct showing soc % in menubar

### ISSUE THREAD

**Issue by mvberkum** [geraldoramos/nikola#16]
Would be great to see the state of charge directly in the menubar next to the car, so you are always aware of it without opening the menubar itself (on osx)

**Comment by geraldoramos** [comment]
nice idea, will put this in my backlog.

**Comment by geraldoramos** [comment]
After thinking a little bit more about this, it won't be possible, sorry.

The application stops polling data from Tesla servers if the main window is not visible. In order to have updated battery data in the tray, we would need to keep polling continuously and this would prevent the car to sleep and could affect battery consumption.

Here is how it currently works:
 - Data updates every 10s if the main window is visible
 - Data updates immediately when the main window is opened.

I will close this since I will not be able to implement it.
