### ISSUE TITLE
Can't open app from the top bar

### ISSUE THREAD

**Issue by EsenbekAliev** [geraldoramos/nikola#28]
I own 2014 Model S , logged in but app won't launch at all, clicking the icon - nothing happens. Does it work only with new M3s?

**Comment by EsenbekAliev** [comment]
Killing the app from Activity Monitor doesn't help after relaunch app still won't work

**Comment by geraldoramos** [comment]
Which version are you using? 

There is an issue with the main window not loading that only happens in some circumstances I could not identify the reason yet. If you have any extra information that could make it helpful, let me know.

Can you try to start the app from the terminal by going to the application folder, then 'Nikola.app/Contents/MacOS, then run `./Nikola` and see if there is any error being logged as the app starts and get stuck?

I happened to me a few times and no error was raised, so I'm kinda stuck on this issue since it's intermittent. I will keep trying to identify the root cause.

**Comment by geraldoramos** [comment]
Opened an issue with Electron team about this.
https://github.com/electron/electron/issues/18877

**Comment by traviscollins** [comment]
I believe I'm running into the same issue. New download today - never used before. Open the app, login, then get a waiting icon and nothing happens. Ran from Terminal and here's the output...

`valcore:MacOS wildag$ ./Nikola 
13:01:51.057 › Nikola App starting...
2019-06-19 13:01:51.149 Nikola[6942:958748] *** WARNING: Textured window <AtomNSWindow: 0x7fbfefc2c9a0> is getting an implicitly transparent titlebar. This will break when linking against newer SDKs. Use NSWindow's -titlebarAppearsTransparent=YES instead.
13:01:51.671 › Checking for update
13:01:51.717 › Hitting Tesla API on Wed Jun 19 2019 13:01:51 GMT-0400 (Eastern Daylight Time)
13:01:52.720 › Update for version 0.3.0 is not available (latest version: 0.3.0, downgrade is disallowed).
13:01:52.721 › checkForUpdatesAndNotify called, downloadPromise is null`

**Comment by geraldoramos** [comment]
Hi @traviscollins, thanks for the report. The error 408 is a Tesla API "busy" error that happens if we do requests too close to each other (if open/close the tray too fast, this can happen) or if you are using another Tesla app (especially the mobile app). If this happens before any data is gathered, it will be loading for a long time trying until it gets the first data from the API. So, I think this is not related to the issue here.

Regarding the issue of sometimes the window becoming invisible (after you log in and the app is running normally), I can't figure out what is going on and what causes it. I reported it in details to the Electron team [here](https://github.com/electron/electron/issues/18877). If it happens to you, the window seems to be still alive, it just gets invisible, if you get to the very top you will see that you can still right click and quit the APP. It's a weird one, I'm trying my best to find a solution asap. It happens suddenly and when it happens, an app restart is required to restore.

The download promise thing is not an issue, it just means you are in the last version and will not attempt to download/update the app. I believe this is the normal behavior for the `electron-builder`  update tool.

**here is a demo of the issue:**

![error](https://user-images.githubusercontent.com/5693297/59795700-09963000-9299-11e9-9c17-c2573c6dc9b9.gif)

**Comment by EsenbekAliev** [comment]
UPDATE: I just reinstalled the app and seems to be no issues, top bar icon always opens the info, not sure what changed, same version as before

**Comment by geraldoramos** [comment]
> UPDATE: I just reinstalled the app and seems to be no issues, top bar icon always opens the info, not sure what changed, same version as before

It eventually happened again with me, it just took a while and happened without any apparent pattern. This issue is pretty tricky, I will continue to investigate and see if Electron guys can give me a hand. Thanks for reporting it.

**Comment by geraldoramos** [comment]
This issue has been fixed. Please update to the [last release](https://github.com/geraldoramos/nikola/releases/latest) when possible!

**Comment by EsenbekAliev** [comment]
thanks, seems to be working now
